### ISSUE TITLE
Conversion to UTM18N (EPSG:32618) fails with cryptic warning

### ISSUE THREAD

**Issue by fghorow** [jobar8/segy2segy#2]
Attempting to convert a seg-y file from a local state plane CRS to UTM (zone 18N if it matters) fails.  

The underlying issue appears to be that after coordinate conversion to UTM, the newXYarray (after line 137 in the segy2segy function) contains floating point values of magnitudes that can not be converted to 4 byte integers. This causes the pack method in ObsPy's SEGYTraceHeader.write() to fail, complaining (quite properly) about its inability to put a value of magnitude 4.7 billion into a 4 byte signed integer.

I don't know how you might want to proceed. Perhaps a warning that converting to a UTM CRS is inappropriate for seg-y files or something???

**Comment by fghorow** [comment]
Never mind. PEBKAC.  Obviously, I'm a newbie with dealing with SEG-Y.  I scaled coordinates, and all is well. Your software is doing its job. Thanks!

**Comment by jobar8** [comment]
Thanks for your comment. Yes, the scaler is an essential part of the SEGY format. Glad you found the solution.
BTW, I am in the process of refactoring and rewriting this piece of software. Hopefully, it will be more reliable and easier to use once this is done.
