### ISSUE TITLE
iline xline offset samples

### ISSUE THREAD

**Issue by SherloK1898989** [jobar8/segy2segy#6]
good afternoon , can you please briefly tell me what xline , iline offset adn samples are . As I understand it , xline is the number of stations from which seismic data was taken , samples is the length of the array of this data , but what is offset and iline ?please clarify if I understood correctly about xline and sample

**Comment by jobar8** [comment]
Hi. As far I remember, xline and iline apply to 3D seismic data. They can be understood as the coordinates of the traces in a horizontal plane. I suggest you search for more complete SEGY specifications.
